# Generated by Django 5.1.2 on 2024-11-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_full_name_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255, verbose_name='Название')),
                ('url_name', models.CharField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Доступный URL',
                'verbose_name_plural': 'Доступные URL',
            },
        ),
        migrations.CreateModel(
            name='SidebarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Группа бокового меню',
                'verbose_name_plural': 'Группы бокового меню',
            },
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.sidebargroup', verbose_name='Группа')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.availableurls', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Элемент бокового меню',
                'verbose_name_plural': 'Элементы бокового меню',
            },
        ),
        migrations.CreateModel(
            name='SidebarItemChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.sidebaritem', verbose_name='Подгруппа')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.availableurls', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Элемент бокового подменю',
                'verbose_name_plural': 'Элементы бокового подменю',
            },
        ),
    ]
