# Generated by Django 4.1.3 on 2023-12-20 18:42

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher_student'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='Наименование курса')),
                ('date_start', models.DateField(verbose_name='Дата начала курса')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('students', models.ManyToManyField(blank=True, null=True, to='account.student', verbose_name='Студенты')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=management.models.upload_materials, verbose_name='Файл')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('task', models.TextField(verbose_name='Задание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=management.models.upload_materials, verbose_name='Файл')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимальный балл')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.course', verbose_name='Курс')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.material', verbose_name='Материал')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.task', verbose_name='Задание'),
        ),
    ]
