# Generated by Django 4.1.3 on 2023-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher_student'),
        ('management', '0002_completedtask_course_material_task_delete_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='account.student', verbose_name='Студенты'),
        ),
    ]
